name: base64-bytestring-type
version: 0.1.0.0
synopsis: A newtype around ByteString, for base64 encoding
description: A newtype around ByteString, for base64 encoding
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-base64-bytestring-type
category: Web
tested-with: GHC==7.8.4, GHC==7.10.2
extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
  - base >=4.7 && <4.9
  - aeson >=0.8 && <0.11
  - binary
  - bytestring
  - base64-bytestring >=1.0 && <1.1
  - cereal >=0.4 && <0.5
  - text >=1.2 && <1.3

library:
  source-dirs: src

tests:
  tests:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - base64-bytestring-type
      - tasty
      - tasty-quickcheck
